# Generated by Django 5.0.7 on 2024-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='total_people',
            new_name='totalPeople',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
